# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vision_info_msg/vision_info_msg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class vision_info_msg(genpy.Message):
  _md5sum = "2e53e466b1aaabe8828aeec7ac1dc68b"
  _type = "vision_info_msg/vision_info_msg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool light
int32 sign
bool blocked
int32 pos
int32 shift
"""
  __slots__ = ['light','sign','blocked','pos','shift']
  _slot_types = ['bool','int32','bool','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       light,sign,blocked,pos,shift

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(vision_info_msg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.light is None:
        self.light = False
      if self.sign is None:
        self.sign = 0
      if self.blocked is None:
        self.blocked = False
      if self.pos is None:
        self.pos = 0
      if self.shift is None:
        self.shift = 0
    else:
      self.light = False
      self.sign = 0
      self.blocked = False
      self.pos = 0
      self.shift = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_BiB2i().pack(_x.light, _x.sign, _x.blocked, _x.pos, _x.shift))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.light, _x.sign, _x.blocked, _x.pos, _x.shift,) = _get_struct_BiB2i().unpack(str[start:end])
      self.light = bool(self.light)
      self.blocked = bool(self.blocked)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_BiB2i().pack(_x.light, _x.sign, _x.blocked, _x.pos, _x.shift))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.light, _x.sign, _x.blocked, _x.pos, _x.shift,) = _get_struct_BiB2i().unpack(str[start:end])
      self.light = bool(self.light)
      self.blocked = bool(self.blocked)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_BiB2i = None
def _get_struct_BiB2i():
    global _struct_BiB2i
    if _struct_BiB2i is None:
        _struct_BiB2i = struct.Struct("<BiB2i")
    return _struct_BiB2i
